// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var ActionHelpers = require("./actionHelpers");

function concatScores(scores) {
  return ActionHelpers.wrap(ActionHelpers.clean(ActionHelpers.concat(scores.map((function (prim) {
                            return ActionHelpers.get(prim);
                          })))));
}

exports.concatScores = concatScores;
/* ./actionHelpers Not a pure module */
