// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var NearleyParser = require("./nearleyParser");

function parse(str) {
  return NearleyParser.parse(str);
}

exports.parse = parse;
/* ./nearleyParser Not a pure module */
