// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var $$Array = require("bs-platform/lib/js/array.js");
var NearleyParser = require("./nearleyParser");

function parse(str) {
  return List.map((function (nearleyParsing) {
                return nearleyParsing;
              }), $$Array.to_list(NearleyParser.parse(str)));
}

exports.parse = parse;
/* ./nearleyParser Not a pure module */
