// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/src/jest.js");
var Parser$UnmusicCore = require("../src/Parser.bs.js");

describe("umscript parser", (function () {
        return Jest.test("can parse an umlang string", (function () {
                      return Jest.ExpectJs[/* toBeTruthy */28](Jest.ExpectJs[/* expect */0](Parser$UnmusicCore.parse("C /16 x=1 >")));
                    }));
      }));

/*  Not a pure module */
